### PR TITLE
From July 2021, the thresholds for energy labels have been changed.

### PR DESCRIPTION
**Pull request by Yorik56**
I propose to modify the default values of the DPE scale in accordance with the new values

source: https://www.immofix.com/nouveau-dpe-quels-changements-au-1er-juillet-2021/

image

### CODE REVIEW

**Comment by bastienlemaitre** [comment]
@pascalz

**Comment by omaroy** [comment]
@Yorik56 @bastienlemaitre If I'm not wrong, Pascal TOUSSAINT passed away at the end of 2017 or the beginning of 2018 I don't remember exactly, I replace him in a .NET project on a automobile company.

**Comment by YvesGeolocaux** [comment]
> @Yorik56 @bastienlemaitre If I'm not wrong, Pascal TOUSSAINT passed away at the end of 2017 or the beginning of 2018 I don't remember exactly, I replace him in a .NET project on a automobile company.

Unfortunately you're right. RIP Pascal

**Comment by Yorik56** [comment]
@omaroy Oh I've only just heard the news, thank you for letting me know and may Pascal rest in peace!

**Pull request closed without merging**
